### ISSUE TITLE
Move from Dat Protocol to Hyperdrive Protocol

### ISSUE THREAD

**Issue by bltavares** [bltavares/colmeia#10]
Dat Protocol is moving into a new version, that is not backward-compatible.

To help to communicate this breaking change [Dat announced it is moving to Hypercore Protocol](https://blog.datproject.org/2020/05/15/dat-protocol-renamed-hypercore-protocol/).

Dat (also known as `dat1` on this repo) will keep existing as is, but the same team that maintained the protocol (also known as `dat2` on this repo) is now focused on adding features only on the new protocol.

Also, [the new Beaker](https://beakerbrowser.com/2020/05/14/beaker-1-0-beta.html) only works on the new protocol, and will migrate the library on previous Dat to Hypercore.

Apps that were targeting Dat will not work with the new protocol, as discovery also changed.

This is tracking issue to move `colmeia` to the Hypercore Protocol:

- [x] Discovery: mdns hyperswarm discovery #11 
  - [x] Fix multi-interface discovery #15 
- [x] Handshake & Exchange with hypercore protocol over network #18 
- [x] Update hypercore version used on the code to the beta releases #21
- [ ] ~Change https://github.com/bltavares/parse-dat-url to `parse-hyper-url`~ #21
  - Removed as hypercore does not have dns resolution anymore https://github.com/beakerbrowser/beaker/discussions/1576
- [x] Move `dat` bins to `hypercore` protocol #21
  - All dat bins moved into `legacy` for historical purpose
  - All previous bins available as `hypercore`
- [x] Move dat1 from the repo to avoid dependencies breaking the latest code
