### ISSUE TITLE
Replicate multiple feeds on a single colmeiad instance

### ISSUE THREAD

**Issue by bltavares** [bltavares/colmeia#24]
The `colmeia-hyperdrive` crate is conflating the storage, peering, hyperdrive and hypercore code.

With @Frando's upcoming `hypercore-replicator`, we should be able to handle multiple replicated feeds, and we can focus on writing only the `hyperdrive` code, without conflating that much.

## TODO Next livestream:

- [x] Split `colmeia-hypercore` into `colmeia-hyperdrive`, and only use `hyperdrive`  code.
- [ ] Adopt `hypercore-replicator` from @Frando on `hyperstack`
- [ ] Adopt updated `hyperstack` on `colmeiad`
- [x] ~*Bonus:* Change protobuf crate to use the same as hypercore protocol (reduce dependencies)~ PROST depends on `protoc`
